/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prestocard;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

//Name: Tinotenda Chibi
//Course: OOP 1
//App Name: Presto Card

/**
 *
 * @author tinot
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    ArrayList<Cards> cards = new ArrayList<>();
    int cardholder = 0;

    public MainFrame() {
//        add the list of cardholders
        cards.add(new Cards("Jacob", 19.00));
        cards.add(new Cards("Nicole", 15.00));
        cards.add(new Cards("Abdi", 39.00));
        cards.add(new Cards("Duncan", 26.00));

        initComponents();

        updateSystem();
    }

    /**
     * Updates the table and table label
     */
    void updateSystem() {
        tableCount.setText("You have " + cards.size() + " card holders.");
        DefaultTableModel model = (DefaultTableModel) prestoTable.getModel();
        model.setRowCount(0);
        //loop through all the cards is the class
        for (int i = 0; i < cards.size(); i++) {

            model.addRow(new Object[]{
                i + 1, cards.get(i).getName(),
                String.format("$%.2f", cards.get(i).getBalance())
            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addFunds = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        AddFundLabel = new javax.swing.JLabel();
        fundSpinner = new javax.swing.JSpinner();
        cancelBtn = new javax.swing.JButton();
        addFundsBtn = new javax.swing.JButton();
        addCard = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        addBalaceSpinner = new javax.swing.JSpinner();
        AddFundLabel1 = new javax.swing.JLabel();
        addName = new javax.swing.JTextField();
        canceladdCard = new javax.swing.JButton();
        addCardHolder = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tableCount = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tapBtn = new javax.swing.JButton();
        topUpBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        prestoTable = new javax.swing.JTable();

        addFunds.setTitle("Add Funds");
        addFunds.setResizable(false);
        addFunds.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                addFundsWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        AddFundLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddFundLabel.setText("Add funds for: ");

        fundSpinner.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        fundSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));
        fundSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(fundSpinner, "$0.00"));

        cancelBtn.setBackground(new java.awt.Color(255, 204, 204));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 0, 0));
        cancelBtn.setText("Cancel");
        cancelBtn.setBorder(null);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        addFundsBtn.setBackground(new java.awt.Color(204, 255, 204));
        addFundsBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addFundsBtn.setForeground(new java.awt.Color(0, 204, 0));
        addFundsBtn.setText("Add Funds +");
        addFundsBtn.setBorder(null);
        addFundsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFundsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addFundsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fundSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AddFundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(AddFundLabel)
                .addGap(26, 26, 26)
                .addComponent(fundSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addFundsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addFundsLayout = new javax.swing.GroupLayout(addFunds.getContentPane());
        addFunds.getContentPane().setLayout(addFundsLayout);
        addFundsLayout.setHorizontalGroup(
            addFundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addFundsLayout.setVerticalGroup(
            addFundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        addCard.setTitle("Add Card Holder");
        addCard.setAlwaysOnTop(true);
        addCard.setFocusCycleRoot(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        addBalaceSpinner.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        addBalaceSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));
        addBalaceSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(addBalaceSpinner, "$0.00"));

        AddFundLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddFundLabel1.setText("Add a new card");

        addName.setText("Card Holders Name");

        canceladdCard.setBackground(new java.awt.Color(255, 204, 204));
        canceladdCard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        canceladdCard.setForeground(new java.awt.Color(255, 0, 0));
        canceladdCard.setText("Cancel");
        canceladdCard.setBorder(null);
        canceladdCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceladdCardActionPerformed(evt);
            }
        });

        addCardHolder.setBackground(new java.awt.Color(204, 255, 204));
        addCardHolder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addCardHolder.setForeground(new java.awt.Color(0, 204, 0));
        addCardHolder.setText("Add Card +");
        addCardHolder.setBorder(null);
        addCardHolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCardHolderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddFundLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(canceladdCard, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addCardHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(addBalaceSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                        .addComponent(addName)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(AddFundLabel1)
                .addGap(18, 18, 18)
                .addComponent(addName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addBalaceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canceladdCard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCardHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addCardLayout = new javax.swing.GroupLayout(addCard.getContentPane());
        addCard.getContentPane().setLayout(addCardLayout);
        addCardLayout.setHorizontalGroup(
            addCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addCardLayout.setVerticalGroup(
            addCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Presto App -Tinotenda Chibi");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setText("Presto Machine");

        tableCount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tableCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tableCount.setText("You have 0 card holders.");

        deleteBtn.setBackground(new java.awt.Color(255, 204, 204));
        deleteBtn.setForeground(new java.awt.Color(255, 0, 0));
        deleteBtn.setText("Delete Card");
        deleteBtn.setBorderPainted(false);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(242, 242, 242));
        jButton2.setText("Add Card +");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tapBtn.setBackground(new java.awt.Color(204, 255, 204));
        tapBtn.setForeground(new java.awt.Color(0, 153, 0));
        tapBtn.setText("Tap Card");
        tapBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));
        tapBtn.setBorderPainted(false);
        tapBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tapBtnActionPerformed(evt);
            }
        });

        topUpBtn.setBackground(new java.awt.Color(242, 242, 242));
        topUpBtn.setText("Top-Up ^");
        topUpBtn.setBorderPainted(false);
        topUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topUpBtnActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prestocard/100px-Presto_Card.svg.png"))); // NOI18N

        prestoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Card Holder", "Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(prestoTable);
        if (prestoTable.getColumnModel().getColumnCount() > 0) {
            prestoTable.getColumnModel().getColumn(0).setResizable(false);
            prestoTable.getColumnModel().getColumn(1).setResizable(false);
            prestoTable.getColumnModel().getColumn(1).setPreferredWidth(200);
            prestoTable.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tapBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(topUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tableCount, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tableCount, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tapBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(topUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void topUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topUpBtnActionPerformed
        int selected = prestoTable.getSelectedRow();

        if (selected == -1) {
            JOptionPane.showMessageDialog(rootPane, "Please select a card to add funds to");
        } else {
            String topUpName = cards.get(selected).getName();
            addFunds.setLocationRelativeTo(this);
            addFunds.pack();
            addFunds.setVisible(true);
            AddFundLabel.setText("Add funds for " + topUpName);
            cardholder = selected;
        }
        
        


    }//GEN-LAST:event_topUpBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        addCard.setLocationRelativeTo(this);
        addCard.pack();
        addCard.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Remove the selected row from the table
     *
     * @param evt
     */
    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int selected = prestoTable.getSelectedRow();

        if (selected == -1) {
            JOptionPane.showMessageDialog(rootPane, "Please select a card to remove");
        } else {
            // Delete from the array list no the array table
            cards.remove(selected);
        }
//       after the item is removed update the list
        updateSystem();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void tapBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tapBtnActionPerformed
//        DefaultTableModel model = (DefaultTableModel) prestoTable.getModel();

        int selected = prestoTable.getSelectedRow();

        if (selected == -1) {
            JOptionPane.showMessageDialog(rootPane, "Please select a card to tap");
        } else {
            if (cards.get(selected).getBalance() < 2.50) {
                JOptionPane.showMessageDialog(rootPane, cards.get(selected).getName() + " does not have suffecient funds.");

            } else {
                double cardBalance = Cards.tap(cards.get(selected).getBalance());
//          model.setValueAt(cardBalance, selected, 2);
                cards.get(selected).setBalance(cardBalance);
                updateSystem();
            }

        }


    }//GEN-LAST:event_tapBtnActionPerformed

    private void addFundsWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_addFundsWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_addFundsWindowGainedFocus

    private void addFundsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFundsBtnActionPerformed
        double addedFunds = (double) fundSpinner.getValue();
        double newBalace = Cards.topUp(addedFunds, cards.get(cardholder).getBalance());
        cards.get(cardholder).setBalance(newBalace);
        fundSpinner.setValue(0.00);
        addFunds.setVisible(false);
        updateSystem();


    }//GEN-LAST:event_addFundsBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        addFunds.setVisible(false);    }//GEN-LAST:event_cancelBtnActionPerformed

    private void canceladdCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceladdCardActionPerformed
        addCard.setVisible(false);

    }//GEN-LAST:event_canceladdCardActionPerformed

    private void addCardHolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCardHolderActionPerformed
        String name = addName.getText();
        double balance = (double)addBalaceSpinner.getValue();
        if("".equals(name)){
            JOptionPane.showMessageDialog(rootPane, "Please insert a name to add as a card holder");
        }
        else{
            cards.add(new Cards(name, balance));
            updateSystem();
            addCard.setVisible(false);
            addName.setText("");
            addBalaceSpinner.setValue(0.00);
        }
    }//GEN-LAST:event_addCardHolderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddFundLabel;
    private javax.swing.JLabel AddFundLabel1;
    private javax.swing.JSpinner addBalaceSpinner;
    private javax.swing.JDialog addCard;
    private javax.swing.JButton addCardHolder;
    private javax.swing.JDialog addFunds;
    private javax.swing.JButton addFundsBtn;
    private javax.swing.JTextField addName;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton canceladdCard;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JSpinner fundSpinner;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable prestoTable;
    private javax.swing.JLabel tableCount;
    private javax.swing.JButton tapBtn;
    private javax.swing.JButton topUpBtn;
    // End of variables declaration//GEN-END:variables
}
